version: '3.8'
services:
  shop-nestjs:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ./shop-nestjs:/home/app
    command: ["npm", "start"]
  e2e-tests:
    image: cypress/included:4.9.0
    depends_on:
      - shop-nestjs
    environment:
      CYPRESS_BASE_URL: 'http://shop-nestjs:3000'
    working_dir: /e2e
    volumes:
      - ./shop-nestjs:/e2e
    user: node
